/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oracle;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author QTrun
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    Statement stmt;
    OracleConnection Oracle;
    public MainForm() {
        setTitle("Trang chính");
        initComponents();
        Oracle = new OracleConnection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_username = new javax.swing.JLabel();
        lbl_last_login = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        showSGA = new javax.swing.JMenuItem();
        showPGA = new javax.swing.JMenuItem();
        ProcessView = new javax.swing.JMenuItem();
        InstanceView = new javax.swing.JMenuItem();
        SessionManager = new javax.swing.JMenuItem();
        Tablespace = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemRole = new javax.swing.JMenuItem();
        menuItemUser = new javax.swing.JMenuItem();
        menuItemProfiles = new javax.swing.JMenuItem();
        menuItemChangePw = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_username.setText("Người dùng:");

        lbl_last_login.setText("Đăng nhập cuối:");
        lbl_last_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("Tệp");

        jMenuItem1.setText("Đăng xuất");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sửa");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");

        showSGA.setText("SGA");
        showSGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSGAActionPerformed(evt);
            }
        });
        jMenu3.add(showSGA);

        showPGA.setText("PGA");
        showPGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPGAActionPerformed(evt);
            }
        });
        jMenu3.add(showPGA);

        ProcessView.setText("Tiến trình");
        ProcessView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessViewActionPerformed(evt);
            }
        });
        jMenu3.add(ProcessView);

        InstanceView.setText("Thuộc tính CSDL");
        InstanceView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstanceViewActionPerformed(evt);
            }
        });
        jMenu3.add(InstanceView);

        SessionManager.setText("Quản lý phiên");
        SessionManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SessionManagerActionPerformed(evt);
            }
        });
        jMenu3.add(SessionManager);

        Tablespace.setText("Tablespace");
        Tablespace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TablespaceActionPerformed(evt);
            }
        });
        jMenu3.add(Tablespace);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tài khoản");

        menuItemRole.setText("Quyền");
        menuItemRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRoleActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemRole);

        menuItemUser.setText("Người dùng");
        menuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUserActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemUser);

        menuItemProfiles.setText("Hồ sơ");
        menuItemProfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProfilesActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemProfiles);

        menuItemChangePw.setText("Đổi mật khẩu");
        menuItemChangePw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemChangePwActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemChangePw);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_last_login, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(lbl_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_last_login)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:  
        try {
            Oracle.openConnection();
            stmt = Oracle.conn.createStatement();
            String sql = "select username from user_users";
            ResultSet rset = stmt.executeQuery(sql);
            rset.next();
            String username = rset.getString(1);
            lbl_username.setText("Username: " + username);
            String querry = "SELECT last_login FROM dba_users WHERE username = '"+ username+ "'";
            rset = stmt.executeQuery(querry);
            rset.next();
            String last_login = rset.getString(1);
            lbl_last_login.setText(String.format("Last Login: %s", last_login));
            rset.close();
            Oracle.closeConnection();            
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_formWindowOpened

    private void showSGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSGAActionPerformed
        // TODO add your handling code here:
        SGA sga = new SGA();
         sga.setVisible(true);
         
    }//GEN-LAST:event_showSGAActionPerformed

    private void showPGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPGAActionPerformed
        // TODO add your handling code here:
        PGA pga = new PGA();
         pga.setVisible(true);
    }//GEN-LAST:event_showPGAActionPerformed

    private void ProcessViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessViewActionPerformed
        // TODO add your handling code here:
         ProcessView fm = new ProcessView();
         fm.setVisible(true);
    }//GEN-LAST:event_ProcessViewActionPerformed

    private void InstanceViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstanceViewActionPerformed
        // TODO add your handling code here:
        Instance fm = new Instance();
         fm.setVisible(true);
    }//GEN-LAST:event_InstanceViewActionPerformed

    private void SessionManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SessionManagerActionPerformed
        // TODO add your handling code here:
        Session fm  = new Session();
        fm.setVisible(true);
    }//GEN-LAST:event_SessionManagerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        OracleConnection conn = new OracleConnection();
        conn.closeConnection();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void TablespaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TablespaceActionPerformed
        // TODO add your handling code here:
        
        
            datafile fm = new datafile();
        fm.setVisible(true);
        
        
    }//GEN-LAST:event_TablespaceActionPerformed

    private void menuItemProfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProfilesActionPerformed
        // TODO add your handling code here:
        ProfileManager fm = new ProfileManager();
        fm.setVisible(true);
    }//GEN-LAST:event_menuItemProfilesActionPerformed

    private void menuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUserActionPerformed
        // TODO add your handling code here:
        UserManager fm  = new UserManager();
        fm.setVisible(true);
    }//GEN-LAST:event_menuItemUserActionPerformed

    private void menuItemChangePwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemChangePwActionPerformed
        // TODO add your handling code here: datafile fm = new datafile();
                    ChangePassword fm = new ChangePassword();

        fm.setVisible(true);
        
    }//GEN-LAST:event_menuItemChangePwActionPerformed

    private void menuItemRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRoleActionPerformed
        // TODO add your handling code here:
        RoleManager fm = new RoleManager();
        fm.setVisible(true);
    }//GEN-LAST:event_menuItemRoleActionPerformed
    
    /**
     * @param args the command line arguments
     */    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Cupertino".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private String username;
            private String password;
            private String url;
            public void run() {
                new MainForm().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem InstanceView;
    private javax.swing.JMenuItem ProcessView;
    private javax.swing.JMenuItem SessionManager;
    private javax.swing.JMenuItem Tablespace;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbl_last_login;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JMenuItem menuItemChangePw;
    private javax.swing.JMenuItem menuItemProfiles;
    private javax.swing.JMenuItem menuItemRole;
    private javax.swing.JMenuItem menuItemUser;
    private javax.swing.JMenuItem showPGA;
    private javax.swing.JMenuItem showSGA;
    // End of variables declaration//GEN-END:variables
}
