/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oracle;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import oracle.model.SanPhamModel;
import oracle.components.SanPhamLayout;
import oracle.model.BanModel;
import oracle.model.ChucVuModel;
import oracle.model.DonHangModel;
import oracle.model.GioHangModel;
import oracle.model.NhanVienModel;
 
/**
 *
 * @author QTrun
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    Statement stmt;
    OracleConnection Oracle;
    ArrayList<SanPhamModel> productModels;
    ArrayList<GioHangModel> cartModels;
    ArrayList<GioHangModel> cartDonHangs;
    
    public MainForm() {
        setTitle("Trang chính");
        initComponents();
        init();
    }
    private void init(){
        Oracle = new OracleConnection();
        cartModels = new ArrayList<>();
        cartDonHangs = new ArrayList<>();
        productModels = new ArrayList<>();
        txt_quantity_order_product.setValue(1);
        loadListProducts();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_username = new javax.swing.JLabel();
        lbl_last_login = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        layout_product = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_product = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_product_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_quantity_order_product = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_cart = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        btn_add_to_cart = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        layout_order = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_don_hang = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_ct_don_hang = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        txt_ma_dh = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_ma_ban = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_ten_nv = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_trang_thai_don = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_tong_tien_dh = new javax.swing.JLabel();
        btn_cap_nhat_dh = new javax.swing.JButton();
        btn_xoa_dh = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        showSGA = new javax.swing.JMenuItem();
        showPGA = new javax.swing.JMenuItem();
        ProcessView = new javax.swing.JMenuItem();
        InstanceView = new javax.swing.JMenuItem();
        SessionManager = new javax.swing.JMenuItem();
        Tablespace = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemRole = new javax.swing.JMenuItem();
        menuItemUser = new javax.swing.JMenuItem();
        menuItemProfiles = new javax.swing.JMenuItem();
        menuItemChangePw = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_username.setText("Người dùng:");

        lbl_last_login.setText("Đăng nhập cuối:");
        lbl_last_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        layout_product.setMaximumSize(new java.awt.Dimension(728, 526));
        layout_product.setRequestFocusEnabled(false);

        table_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "ID", "Tên Sản Phẩm", "Giá", "Tồn Kho"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_productMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(table_product);

        jLabel1.setText("Tên sản phẩm:");

        jLabel2.setText("Số lượng:");

        jScrollPane1.setViewportView(list_cart);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tổng tiền");

        txt_total.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_total.setText("0");

        btn_add_to_cart.setText("Thêm vào giỏ");
        btn_add_to_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_to_cartActionPerformed(evt);
            }
        });

        jButton1.setText("Tạo đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout_productLayout = new javax.swing.GroupLayout(layout_product);
        layout_product.setLayout(layout_productLayout);
        layout_productLayout.setHorizontalGroup(
            layout_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout_productLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout_productLayout.createSequentialGroup()
                        .addGroup(layout_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_product_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout_productLayout.createSequentialGroup()
                                .addComponent(txt_quantity_order_product, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btn_add_to_cart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout_productLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout_productLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout_productLayout.setVerticalGroup(
            layout_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout_productLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txt_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout_productLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout_productLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_quantity_order_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout_productLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(btn_add_to_cart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tạo đơn", layout_product);

        table_don_hang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ĐH", "Bàn", "Tổng Tiền", "Nhân Viên", "Trạng Thái", "TG Đặt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_don_hang);
        if (table_don_hang.getColumnModel().getColumnCount() > 0) {
            table_don_hang.getColumnModel().getColumn(1).setMinWidth(50);
            table_don_hang.getColumnModel().getColumn(1).setMaxWidth(50);
        }

        jScrollPane4.setViewportView(list_ct_don_hang);

        jLabel4.setText("Mã ĐH:");

        txt_ma_dh.setText("01");

        jLabel5.setText("Bàn:");

        txt_ma_ban.setText("01");

        jLabel7.setText("Nhân Viên:");

        txt_ten_nv.setText("Nguyễn Tri Long");

        jLabel9.setText("Trạng Thái:");

        cb_trang_thai_don.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa Thanh Toán", "Đã Thanh Toán" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("TỔNG TIỀN");

        txt_tong_tien_dh.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_tong_tien_dh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_tong_tien_dh.setText("10,000,000đ");

        btn_cap_nhat_dh.setText("Cập nhật đơn");

        btn_xoa_dh.setText("Xóa đơn");

        javax.swing.GroupLayout layout_orderLayout = new javax.swing.GroupLayout(layout_order);
        layout_order.setLayout(layout_orderLayout);
        layout_orderLayout.setHorizontalGroup(
            layout_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout_orderLayout.createSequentialGroup()
                .addGroup(layout_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout_orderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout_orderLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout_orderLayout.createSequentialGroup()
                                .addComponent(btn_cap_nhat_dh, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(btn_xoa_dh, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout_orderLayout.createSequentialGroup()
                                .addGroup(layout_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_ma_dh, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(txt_ma_ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(98, 98, 98)
                                .addGroup(layout_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_trang_thai_don, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout_orderLayout.createSequentialGroup()
                                        .addComponent(txt_ten_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(layout_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout_orderLayout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout_orderLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(txt_tong_tien_dh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout_orderLayout.setVerticalGroup(
            layout_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout_orderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(18, 18, 18)
                .addGroup(layout_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_ma_dh)
                    .addComponent(jLabel7)
                    .addComponent(txt_ten_nv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_ma_ban)
                    .addComponent(jLabel9)
                    .addComponent(cb_trang_thai_don, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tong_tien_dh, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xoa_dh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cap_nhat_dh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Đơn hàng", layout_order);

        jMenu1.setText("Tệp");

        jMenuItem1.setText("Đăng xuất");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sửa");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");

        showSGA.setText("SGA");
        showSGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSGAActionPerformed(evt);
            }
        });
        jMenu3.add(showSGA);

        showPGA.setText("PGA");
        showPGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPGAActionPerformed(evt);
            }
        });
        jMenu3.add(showPGA);

        ProcessView.setText("Tiến trình");
        ProcessView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessViewActionPerformed(evt);
            }
        });
        jMenu3.add(ProcessView);

        InstanceView.setText("Thuộc tính CSDL");
        InstanceView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstanceViewActionPerformed(evt);
            }
        });
        jMenu3.add(InstanceView);

        SessionManager.setText("Quản lý phiên");
        SessionManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SessionManagerActionPerformed(evt);
            }
        });
        jMenu3.add(SessionManager);

        Tablespace.setText("Tablespace");
        Tablespace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TablespaceActionPerformed(evt);
            }
        });
        jMenu3.add(Tablespace);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tài khoản");

        menuItemRole.setText("Quyền");
        menuItemRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRoleActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemRole);

        menuItemUser.setText("Người dùng");
        menuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUserActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemUser);

        menuItemProfiles.setText("Hồ sơ");
        menuItemProfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProfilesActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemProfiles);

        menuItemChangePw.setText("Đổi mật khẩu");
        menuItemChangePw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemChangePwActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemChangePw);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_last_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_last_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void showSGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSGAActionPerformed
        // TODO add your handling code here:
        SGA sga = new SGA();
         sga.setVisible(true);
         
    }//GEN-LAST:event_showSGAActionPerformed

    private void showPGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPGAActionPerformed
        // TODO add your handling code here:
        PGA pga = new PGA();
         pga.setVisible(true);
    }//GEN-LAST:event_showPGAActionPerformed

    private void ProcessViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessViewActionPerformed
        // TODO add your handling code here:
         ProcessView fm = new ProcessView();
         fm.setVisible(true);
    }//GEN-LAST:event_ProcessViewActionPerformed

    private void InstanceViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstanceViewActionPerformed
        // TODO add your handling code here:
        Instance fm = new Instance();
         fm.setVisible(true);
    }//GEN-LAST:event_InstanceViewActionPerformed

    private void SessionManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SessionManagerActionPerformed
        // TODO add your handling code here:
        Session fm  = new Session();
        fm.setVisible(true);
    }//GEN-LAST:event_SessionManagerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        OracleConnection conn = new OracleConnection();
        conn.closeConnection();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void TablespaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TablespaceActionPerformed
        // TODO add your handling code here:
        
        
            datafile fm = new datafile();
        fm.setVisible(true);
        
        
    }//GEN-LAST:event_TablespaceActionPerformed

    private void menuItemProfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProfilesActionPerformed
        // TODO add your handling code here:
        ProfileManager fm = new ProfileManager();
        fm.setVisible(true);
    }//GEN-LAST:event_menuItemProfilesActionPerformed

    private void menuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUserActionPerformed
        // TODO add your handling code here:
        UserManager fm  = new UserManager();
        fm.setVisible(true);
    }//GEN-LAST:event_menuItemUserActionPerformed

    private void menuItemChangePwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemChangePwActionPerformed
        // TODO add your handling code here: datafile fm = new datafile();
                    ChangePassword fm = new ChangePassword();

        fm.setVisible(true);
        
    }//GEN-LAST:event_menuItemChangePwActionPerformed

    private void menuItemRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRoleActionPerformed
        // TODO add your handling code here:
        RoleManager fm = new RoleManager();
        fm.setVisible(true);
    }//GEN-LAST:event_menuItemRoleActionPerformed

    private void table_productMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_productMousePressed
        // TODO add your handling code here:
        String name_product = (String) table_product.getValueAt(table_product.getSelectedRow(), 2);
        txt_product_name.setText(name_product);
    }//GEN-LAST:event_table_productMousePressed

    private void btn_add_to_cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_to_cartActionPerformed
        // TODO add your handling code here:
        // Lay san pham duoc chon
        int id_selected = (int) table_product.getValueAt(table_product.getSelectedRow(), 1);
        SanPhamModel productModel = new SanPhamModel();
        for (SanPhamModel item : productModels) {
            if (item.getMaSP() == id_selected) {
                productModel = item;
                break;
            }
        }
        // kiem tra sp duoc chon da co trong gio hang chua
        boolean flag = false;
        for (int i = 0; i < cartModels.size(); i++) {
            GioHangModel cartModel = cartModels.get(i);
            if (cartModel.getProductModel() == productModel) {
                int newQuan = cartModel.getSoLuong()+ (int) txt_quantity_order_product.getValue();
                cartModels.get(i).setSoLuong(newQuan);
                flag = true;
                break;
            }
        }
        
        if (!flag) {
            // chua co trong gio hang => them moi
            cartModels.add(new GioHangModel(productModel, (int) txt_quantity_order_product.getValue()));
        }
            
        // Cap nhat len listview cart
        updateListViewCart(cartModels);
        updateTotalBill(cartModels);
        txt_quantity_order_product.setValue(1);
    }//GEN-LAST:event_btn_add_to_cartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, cartModels);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void updateListViewCart(ArrayList<GioHangModel> cartModels){
        list_cart.removeAll();
        DefaultListModel defaultListModel = new DefaultListModel();
        for (GioHangModel cartModel : cartModels) {
            defaultListModel.addElement(
                    cartModel.getProductModel().getTenSP()+
                            " x" +
                            cartModel.getSoLuong()+ " " +
                            formatNumber(cartModel.getSoLuong()* cartModel.getProductModel().getGiaSP()) + "đ"
                            
            );
        }
        list_cart.setModel(defaultListModel);
    }
    
    private void updateTotalBill(ArrayList<GioHangModel> cartModels){
        float total = 0;
        for (GioHangModel cartModel : cartModels) {
            total += cartModel.getSoLuong()* cartModel.getProductModel().getGiaSP();
        }
        txt_total.setText(formatNumber(total) + " đ");
    }
    
    private void loadListProducts(){
        // TODO add your handling code here:  
        this.productModels.add(new SanPhamModel(0, "Cà phê sữa", 20000,10, getClass().getResource("/oracle/assets/images/7up.jpg").toString()));
        this.productModels.add(new SanPhamModel(1, "Cà phê đá", 20000,20, "./assets/images/7up.jpg"));
        this.productModels.add(new SanPhamModel(2, "Nước Cam", 15000,31, "./assets/images/7up.jpg"));
        this.productModels.add(new SanPhamModel(3, "Soda", 20000,13, "./assets/images/7up.jpg"));
        this.productModels.add(new SanPhamModel(4, "Nước lọc", 10000,22, "./assets/images/7up.jpg"));
        try {
            Oracle.openConnection();
            stmt = Oracle.conn.createStatement();
            String sql = "select username from user_users";
            ResultSet rset = stmt.executeQuery(sql);
            rset.next();
            String username = rset.getString(1);
            lbl_username.setText("Username: " + username);
            String querry = "SELECT last_login FROM dba_users WHERE username = '"+ username+ "'";
            rset = stmt.executeQuery(querry);
            rset.next();
            String last_login = rset.getString(1);
            lbl_last_login.setText(String.format("Last Login: %s", last_login));
            rset.close();
            Oracle.closeConnection();            
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//       Tao dt productlayout
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("");
        tableModel.addColumn("ID");
        tableModel.addColumn("Tên Sản Phẩm");
        tableModel.addColumn("Giá");
        tableModel.addColumn("Số lượng tồn");
        for (SanPhamModel productModel : productModels) {
            tableModel.addRow(new Object[]{
                new ImageIcon(productModel.getHinhAnh()),
                productModel.getMaSP(),
                productModel.getTenSP(),
                formatNumber(productModel.getGiaSP()) + "đ",
                productModel.getSoLuongTon()
            });
        }
        table_product.setModel(tableModel);
        table_product.setRowHeight(50);
//        set hien thi hinh anh cho cot 0
        table_product.getColumnModel().getColumn(0).setCellRenderer(new ImageRenderer());
//        set width choc ac cot
        table_product.getColumnModel().getColumn(0).setMinWidth(100);
        table_product.getColumnModel().getColumn(0).setMaxWidth(100);
        table_product.getColumnModel().getColumn(1).setPreferredWidth(5);
        table_product.getColumnModel().getColumn(2).setPreferredWidth(250);
        table_product.getColumnModel().getColumn(3).setPreferredWidth(30);
        table_product.getColumnModel().getColumn(4).setPreferredWidth(10);
        table_product.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }
    
    private void removeCartItem(int idProduct){
        GioHangModel cartModel = new GioHangModel();
        for (GioHangModel item : cartModels) {
            if (item.getProductModel().getMaSP() == idProduct) {
                cartModels.remove(item);
                break;
            }
        }
    }
    
    private void loadListOrder(JTable table){
        ArrayList<DonHangModel> donHangModels = new ArrayList<>();
    // TODO add your handling code here: 
        ChucVuModel chucVuModel = new ChucVuModel(0, "Quan Ly", "");
        NhanVienModel nhanVienModel = new NhanVienModel(0, "Nguyen Tri Long", 100000, chucVuModel);
        BanModel banModel = new BanModel(0, 3, 0);
        donHangModels.add(new DonHangModel(0, "17-04-2023 10:10:10", 0,100000, nhanVienModel,"",banModel));
        donHangModels.add(new DonHangModel(1, "17-04-2023 10:10:10", 1,100000, nhanVienModel,"",banModel));        
        donHangModels.add(new DonHangModel(2, "17-04-2023 10:10:10", 0,100000, nhanVienModel,"",banModel));        
        donHangModels.add(new DonHangModel(3, "17-04-2023 10:10:10", 1,100000, nhanVienModel,"",banModel));        
        donHangModels.add(new DonHangModel(4, "17-04-2023 10:10:10", 0,100000, nhanVienModel,"",banModel));        
        try {
            Oracle.openConnection();
            stmt = Oracle.conn.createStatement();
            String sql = "select username from user_users";
            ResultSet rset = stmt.executeQuery(sql);
            rset.next();
            String username = rset.getString(1);
            lbl_username.setText("Username: " + username);
            String querry = "SELECT last_login FROM dba_users WHERE username = '"+ username+ "'";
            rset = stmt.executeQuery(querry);
            rset.next();
            String last_login = rset.getString(1);
            lbl_last_login.setText(String.format("Last Login: %s", last_login));
            rset.close();
            Oracle.closeConnection();            
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//       Tao dt productlayout
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("");
        tableModel.addColumn("ID");
        tableModel.addColumn("Tên Sản Phẩm");
        tableModel.addColumn("Giá");
        tableModel.addColumn("Số lượng tồn");
        for (SanPhamModel productModel : productModels) {
            tableModel.addRow(new Object[]{
                new ImageIcon(productModel.getHinhAnh()),
                productModel.getMaSP(),
                productModel.getTenSP(),
                formatNumber(productModel.getGiaSP()) + "đ",
                productModel.getSoLuongTon()
            });
        }
        table_product.setModel(tableModel);
        table_product.setRowHeight(50);
//        set hien thi hinh anh cho cot 0
        table_product.getColumnModel().getColumn(0).setCellRenderer(new ImageRenderer());
//        set width choc ac cot
        table_product.getColumnModel().getColumn(0).setMinWidth(100);
        table_product.getColumnModel().getColumn(0).setMaxWidth(100);
        table_product.getColumnModel().getColumn(1).setPreferredWidth(5);
        table_product.getColumnModel().getColumn(2).setPreferredWidth(250);
        table_product.getColumnModel().getColumn(3).setPreferredWidth(30);
        table_product.getColumnModel().getColumn(4).setPreferredWidth(10);
        table_product.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }
    
    private String formatNumber(Object number){
        return new DecimalFormat("#,###").format(number);
    }
        
    /**
     * @param args the command line arguments
     */    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Cupertino".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private String username;
            private String password;
            private String url;
            public void run() {
                new MainForm().setVisible(true);
            }
        });
        
        
    
    }
    
    // Tạo một TableCellRenderer tùy chỉnh cho việc hiển thị hình ảnh
    class ImageRenderer extends JLabel implements TableCellRenderer {
        public ImageRenderer() {
            setOpaque(true);
        }

        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            if (value instanceof ImageIcon) {
                // Nếu giá trị là ImageIcon, thiết lập nó làm biểu tượng cho nhãn
                setIcon((ImageIcon) value);
            } else {
                // Nếu không phải, thiết lập văn bản cho nhãn
                setText((value == null) ? "" : value.toString());
            }
            return this;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem InstanceView;
    private javax.swing.JMenuItem ProcessView;
    private javax.swing.JMenuItem SessionManager;
    private javax.swing.JMenuItem Tablespace;
    private javax.swing.JButton btn_add_to_cart;
    private javax.swing.JButton btn_cap_nhat_dh;
    private javax.swing.JButton btn_xoa_dh;
    private javax.swing.JComboBox<String> cb_trang_thai_don;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel layout_order;
    private javax.swing.JPanel layout_product;
    private javax.swing.JLabel lbl_last_login;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JList<String> list_cart;
    private javax.swing.JList<String> list_ct_don_hang;
    private javax.swing.JMenuItem menuItemChangePw;
    private javax.swing.JMenuItem menuItemProfiles;
    private javax.swing.JMenuItem menuItemRole;
    private javax.swing.JMenuItem menuItemUser;
    private javax.swing.JMenuItem showPGA;
    private javax.swing.JMenuItem showSGA;
    private javax.swing.JTable table_don_hang;
    private javax.swing.JTable table_product;
    private javax.swing.JLabel txt_ma_ban;
    private javax.swing.JLabel txt_ma_dh;
    private javax.swing.JLabel txt_product_name;
    private javax.swing.JSpinner txt_quantity_order_product;
    private javax.swing.JLabel txt_ten_nv;
    private javax.swing.JLabel txt_tong_tien_dh;
    private javax.swing.JLabel txt_total;
    // End of variables declaration//GEN-END:variables
}
